(()=>{
const D={
'computer-basics':{
level:'Foundations → Runtime',prerequisites:['None'],objectives:['Explain the roles of CPU, registers, RAM, storage, operating system, process and I/O.','Trace a program from source file to execution at a conceptual level.','Distinguish persistent state from working state and computation from I/O.'],
problem:'A web developer eventually depends on machines doing work. Without a machine-level model, performance problems, crashes, memory behavior and operating-system boundaries look arbitrary.',
history:'Early computers were programmed close to hardware. Higher-level languages, operating systems and managed runtimes progressively hid machine details so developers could focus on problems. The abstractions remain useful because the underlying costs still exist.',
think:'Imagine a program as a recipe for changing state. The CPU performs instructions, memory holds active state, storage preserves data, and the operating system controls access to resources. The abstractions make programming practical; they do not make the physical work disappear.',
concepts:[['CPU','Executes instructions and performs operations. Modern CPUs contain multiple cores and several levels of cache.'],['Registers','Tiny, extremely fast storage locations used directly by CPU instructions.'],['RAM','Working memory for active programs and data; volatile and much faster than persistent storage.'],['Storage','Persistent bytes on SSD, HDD or other media.'],['Process','An operating-system execution boundary containing program state and resources.'],['I/O','Work that crosses a boundary to storage, network, devices or another process.']],
flow:['Source code exists as text.','A compiler/interpreter/runtime turns source or intermediate representation into executable work.','The operating system creates or starts a process and gives it resources.','Instructions execute on CPU cores while active data is held in memory.','I/O requests leave the CPU and interact with operating-system services and devices.','Results become new state, output, or further I/O.'],
example:'const price=1200;\nconst tax=price*0.18;\nconst total=price+tax;\nconsole.log(total);',
walkthrough:['price and tax are values represented by the language runtime.','The multiplication and addition become executable operations.','console.log is not a CPU primitive; it eventually reaches a runtime and output mechanism.','The exact placement of values in registers, stack, heap or optimized representations depends on the runtime and compiler.'],
failures:['Assuming RAM and storage have the same latency or persistence.','Assuming every source-level variable maps directly to a fixed memory location.','Ignoring I/O when explaining application latency.','Treating a process and a thread as interchangeable.'],
performance:'CPU work, memory access, allocation, garbage collection, system calls, disk I/O and network latency have different cost profiles. Production performance work begins by measuring which boundary dominates instead of guessing.',
security:'The operating system isolates processes and mediates access to files, devices and networks. Application security builds on these boundaries but cannot assume they remove every risk.',
accessibility:'Machine fundamentals indirectly affect accessibility: responsive applications must manage CPU, memory and network work so assistive technology users are not trapped behind long stalls or excessive client-side processing.',
production:'A production service must have bounded resource use, graceful failure, logging, health checks, timeouts and clear ownership of external resources.',
debugging:['Reproduce the behavior.','Decide whether the dominant work is CPU, memory, disk, network or synchronization.','Measure before optimizing.','Inspect process/resource metrics.','Change one variable and verify the result.'],
exercises:['Draw the path of a file read from application code to persistent storage and back.','Compare a CPU-bound loop with a network request and explain why their latency behaves differently.','Inspect one running process and record its memory and CPU usage.'],
mastery:'You can explain the machine/runtime/OS boundary precisely and use that model to investigate real application behavior.',
quiz:[['Which resource is normally persistent after power loss?','Storage'],['What is the main execution unit of a CPU?','Instructions'],['Why does I/O often dominate latency?','It crosses comparatively slow external boundaries such as storage or networks.']]
},
'binary-data':{
level:'Foundations → Representation',prerequisites:['How Computers Work'],objectives:['Convert between bits, bytes, binary and hexadecimal.','Explain why text requires an encoding.','Understand serialization and why representation is separate from meaning.'],
problem:'Software moves information between memory, files, databases and networks. All of those boundaries ultimately carry bytes, so bugs often come from interpreting the same bytes differently.',
history:'Digital systems adopted binary because reliable electronic switching naturally maps to discrete states. Character encodings evolved from limited character sets toward Unicode and variable-width encodings such as UTF-8 to represent global text.',
think:'A byte sequence is raw material. Meaning is supplied by a contract. The contract might say “interpret these bytes as UTF-8 text”, “decode these bytes as a PNG”, or “read four bytes as a 32-bit integer”.',
concepts:[['Bit','A binary state with two possible values.'],['Byte','Eight bits, allowing 256 distinct patterns.'],['Hexadecimal','Base-16 notation; one digit represents four bits.'],['Unicode','A standard for representing characters and code points across writing systems.'],['UTF-8','A variable-width encoding that represents Unicode code points as one to four bytes.'],['Serialization','Turning structured values into a representation suitable for storage or transport.']],
flow:['Start with a value or structure in a program.','Choose a representation/encoding.','Encode into bytes.','Transmit or store the bytes.','Decode using the agreed format.','Interpret the resulting values.'],
example:'const n=255;\nconsole.log(n.toString(2));\nconsole.log(n.toString(16));\nconst bytes=new TextEncoder().encode(\'web\');\nconsole.log([...bytes]);',
walkthrough:['255 becomes 11111111 in binary and ff in hexadecimal.','TextEncoder applies UTF-8 to the string.','The resulting Uint8Array contains bytes, not characters.','Decoding those bytes requires the same encoding contract.'],
failures:['Assuming one character always equals one byte.','Mixing encodings and producing mojibake.','Confusing hexadecimal notation with a different numeric value.','Parsing untrusted serialized data without validating structure or size.'],
performance:'Binary formats can reduce bandwidth and storage compared with verbose text, but compression and parsing have CPU costs. Choose representations based on interoperability, size, CPU cost and debugging needs.',
security:'Serialization is a trust boundary. Validate lengths, types and nesting depth before processing attacker-controlled data. Never deserialize arbitrary executable object formats without a clear security model.',
accessibility:'Correct Unicode handling is foundational for names, languages, screen-reader output, right-to-left text and internationalized interfaces.',
production:'Define encoding and serialization contracts explicitly at API and file boundaries. Test Unicode, empty values, malformed bytes, large payloads and compatibility across versions.',
debugging:['Inspect the raw bytes.','Confirm the expected encoding or format.','Decode with an explicit contract.','Compare byte length with character count.','Test malformed and non-ASCII input.'],
exercises:['Encode “é” and an emoji with TextEncoder and compare byte lengths.','Convert 0–31 from decimal to binary and hexadecimal.','Design a tiny message format and document its byte-level contract.'],
mastery:'You can explain representation independently from meaning and diagnose encoding, size and serialization failures.',
quiz:[['How many bits are in a byte?','8'],['Why can one visible character use multiple UTF-8 bytes?','UTF-8 is variable-width and encodes Unicode code points using different byte counts.'],['What gives a byte sequence its meaning?','A format or encoding contract.']]
},
'memory-processes':{
level:'Deep Dive → Operating System',prerequisites:['How Computers Work'],objectives:['Explain process isolation and thread sharing.','Describe stack, heap and virtual memory at a useful conceptual level.','Distinguish concurrency from parallelism.'],
problem:'Many programs need to run simultaneously while remaining isolated. The operating system must provide each program an execution environment without letting one ordinary process freely corrupt another.',
history:'Early systems offered little isolation. Modern operating systems introduced virtual memory, process isolation, scheduling and protection rings to let many applications share hardware more safely.',
think:'A process is a protected workspace for execution. Threads are workers inside that workspace. Threads share much of the process memory, which makes communication efficient but makes accidental shared-state races possible.',
concepts:[['Virtual memory','An address-space abstraction that separates a process view of memory from physical memory.'],['Stack','Memory commonly associated with call frames and short-lived execution state.'],['Heap','Memory used for dynamically managed objects whose lifetime is not tied to one call frame.'],['Thread','An execution path sharing a process address space.'],['Context switch','Changing which execution context is actively running on a CPU.'],['Concurrency','Multiple tasks making progress over overlapping periods; not necessarily simultaneously on separate cores.']],
flow:['Program starts as a process.','The OS establishes an address space and resources.','One or more threads execute instructions.','Threads read and mutate shared state.','The scheduler decides when runnable work receives CPU time.','Blocking I/O allows other work to proceed depending on the runtime and architecture.'],
example:'function outer(){\n  const message=\'hello\';\n  return ()=>message;\n}\nconst read=outer();\nconsole.log(read());',
walkthrough:['outer creates a local binding.','The returned function retains access to that binding through a closure.','The JavaScript runtime manages the lifetime of the captured value.','This illustrates language-level lifetime; it should not be mistaken for a literal diagram of physical stack/heap placement.'],
failures:['Calling every asynchronous operation a thread.','Assuming concurrency always means parallel CPU execution.','Sharing mutable state without synchronization in multithreaded systems.','Ignoring memory retention caused by long-lived references.'],
performance:'Context switching, cache locality, allocation, synchronization and memory pressure affect throughput. More threads are not automatically faster; contention and coordination can dominate.',
security:'Process isolation is a major security boundary. Least privilege, sandboxing and OS permissions reduce the blast radius of compromised application components.',
accessibility:'Long CPU stalls, memory pressure and blocked main-thread work can make interfaces unusable. Browser accessibility therefore intersects with runtime scheduling and resource management.',
production:'Services need memory limits, worker/process supervision, graceful shutdown and protection against unbounded queues. Measure resident memory, CPU saturation and event-loop delay where applicable.',
debugging:['Check whether the issue is CPU, memory, blocking I/O or contention.','Capture process/thread metrics.','Look for retained objects and growing queues.','For concurrency bugs, make shared state and ordering assumptions explicit.'],
exercises:['Explain why two processes normally cannot read each other’s private memory directly.','Create a small program that grows memory and observe resource usage.','Describe a race condition involving two workers updating one shared counter.'],
mastery:'You can reason about execution boundaries, memory lifetime and concurrency without reducing them to misleading one-line rules.',
quiz:[['Do threads in one process normally share address space?','Yes'],['Does concurrency require multiple CPU cores?','No'],['Why can more threads reduce performance?','Coordination, contention, context switching and resource pressure can outweigh parallel work.']]
},
'programming-fundamentals':{
level:'Foundations → Problem Solving',prerequisites:['How Computers Work','Bits, Bytes and Data'],objectives:['Translate vague requirements into explicit inputs, state, rules and outputs.','Use control flow and functions to make behavior testable.','Treat errors and edge cases as part of a program contract.'],
problem:'A computer cannot execute “handle the customer order” as a vague intention. Programming turns ambiguous goals into precise state transitions that can be checked.',
history:'Programming evolved from direct machine instructions toward assembly, procedural languages, object-oriented languages, functional techniques and declarative systems. The syntax changes; decomposition and precise state remain central.',
think:'Before writing syntax, answer four questions: What enters the system? What state changes? What rules determine those changes? What output proves success or failure?',
concepts:[['Value','A piece of data used by a program.'],['State','Information whose current value affects future behavior.'],['Control flow','The path execution takes through decisions, repetition and calls.'],['Function','A named behavior with inputs and an output contract.'],['Invariant','A condition that should remain true during or after an operation.'],['Error','A condition in which the intended contract cannot be completed normally.']],
flow:['Define the requirement.','Identify inputs and outputs.','Model state and invariants.','Choose data structures.','Write the smallest clear algorithm.','Validate normal and abnormal cases.','Test and observe behavior.'],
example:'function calculateTotal(items,taxRate){\n  let subtotal=0;\n  for(const item of items){\n    subtotal+=item.price*item.quantity;\n  }\n  return subtotal*(1+taxRate);\n}',
walkthrough:['The function accepts a collection and a tax rule.','subtotal is state that changes as items are processed.','Each item contributes price × quantity.','The return value is the final contract output.','Production code would also define valid ranges, currency precision, empty inputs and invalid items.'],
failures:['Writing code before clarifying the contract.','Using mutable state when a simpler transformation exists.','Testing only the happy path.','Swallowing errors and returning misleading success values.'],
performance:'Prefer algorithms and structures appropriate to input size. Avoid optimizing syntax before identifying the dominant operation. For financial calculations, correctness and numeric representation can matter more than micro-optimizations.',
security:'Treat every external input as untrusted. Validate types, ranges, lengths and authorization separately. Never confuse validation with permission to perform an action.',
accessibility:'When programming UI behavior, keyboard, focus, semantics and reduced-motion preferences are part of the functional contract, not optional decoration.',
production:'Production functions need explicit contracts, tests, telemetry around important failures, predictable errors and safe handling of unexpected inputs.',
debugging:['Reduce the failing input.','Write down expected versus actual state.','Find the first incorrect transition.','Fix the cause rather than masking the symptom.','Add a regression test.'],
exercises:['Model an invoice as inputs, state, rules and outputs before coding.','Write tests for empty, negative, huge and malformed inputs.','Refactor one long function into smaller functions with explicit contracts.'],
mastery:'You can decompose real requirements into executable, testable behavior before selecting framework features.',
quiz:[['What should you define before implementation?','Inputs, state, rules, outputs and failure cases.'],['Why are invariants useful?','They provide conditions that help reason about correctness.'],['What is a regression test?','A test that prevents a previously fixed failure from returning.']]
},
'data-structures':{
level:'Core → Data Modeling',prerequisites:['How Programs Work'],objectives:['Choose data structures based on dominant operations.','Explain the practical trade-offs of arrays, maps, sets, stacks, queues, trees and graphs.','Connect representation choices to complexity and memory.'],
problem:'The same information can be represented many ways. The representation determines which operations are natural, costly, or error-prone.',
history:'Data structures emerged alongside algorithmic computing because efficient computation depends on how data is organized. Modern languages provide standard structures, but the underlying trade-offs remain.',
think:'Do not ask “Which structure is best?” Ask “Which operations must be fast, which relationships must be preserved, and what memory trade-off is acceptable?”',
concepts:[['Array','Indexed sequence; excellent for ordered iteration and compact contiguous-style storage.'],['Map','Key-to-value association for keyed access.'],['Set','Unique membership collection.'],['Stack','Last-in-first-out sequence.'],['Queue','First-in-first-out sequence.'],['Tree','Hierarchical structure with parent/child relationships.'],['Graph','General network of nodes and edges.']],
flow:['List required operations.','Estimate data size and access frequency.','Select a representation.','Analyze time and memory costs.','Measure real workload behavior.'],
example:'const usersById=new Map();\nusersById.set(\'u1\',{name:\'Asha\'});\nconst roles=new Set([\'admin\',\'editor\',\'admin\']);',
walkthrough:['Map expresses the requirement “find user by ID”.','Set expresses “store each role once”.','The representation makes the intended operation visible in the code.','The exact performance depends on implementation and workload, but the abstraction provides the expected operation semantics.'],
failures:['Using arrays for repeated keyed lookup at large scale without considering cost.','Using objects when arbitrary keys or insertion semantics require a Map.','Building elaborate trees when the workload does not benefit from them.','Forgetting memory overhead when trading time for faster lookup.'],
performance:'Expected constant-time Map/Set lookup is not a universal guarantee of identical real-world latency. Hashing, collisions, allocation, cache locality and workload distribution matter. Benchmark representative data.',
security:'Data structure choices can affect denial-of-service exposure. Unbounded maps, queues and caches can consume memory when attackers control cardinality.',
accessibility:'UI data structures should preserve meaningful order and relationships. A visually sorted list is not enough if DOM order and keyboard navigation disagree.',
production:'Choose structures around actual access patterns, document important complexity assumptions, cap unbounded collections and monitor memory.',
debugging:['Inspect the actual shape of data.','Check invariants such as uniqueness and ordering.','Measure operation counts.','Replace the structure only after identifying the dominant cost.'],
exercises:['Implement a frequency counter with Map.','Implement a queue and stack.','Model a dependency graph and perform breadth-first traversal.'],
mastery:'You can justify a representation from workload requirements and explain the time, memory and correctness consequences.',
quiz:[['What structure represents unique membership?','Set'],['What structure models key/value lookup?','Map'],['What determines the appropriate data structure?','Required operations, scale, relationships, correctness and resource constraints.']]
},
'algorithms':{
level:'Core → Reasoning',prerequisites:['Data Structures'],objectives:['Turn requirements into explicit algorithms.','Use search, sorting and traversal correctly.','Reason about correctness, assumptions and edge cases.'],
problem:'Programs need repeatable procedures. An algorithm makes a solution precise enough to implement, test and analyze.',
history:'Algorithmic ideas predate modern computers, but computer science formalized procedures for searching, sorting, optimization and graph traversal. Algorithm design remains a bridge between requirements and implementation.',
think:'Define the output first. Then identify what information must be known to produce it, what work can be reused, and what assumptions make the procedure valid.',
concepts:[['Linear search','Checks candidates sequentially.'],['Binary search','Repeatedly halves a sorted search space.'],['Sorting','Reorders data according to an ordering relation.'],['Traversal','Systematically visits nodes in a structure.'],['Invariant','A property maintained while an algorithm runs.'],['Edge case','An input near a boundary or unusual condition that can expose incorrect assumptions.']],
flow:['Specify input/output contract.','Identify preconditions.','Choose representation.','Design steps.','State invariant or correctness argument.','Test boundaries.','Analyze complexity.'],
example:'function binarySearch(values,target){\n  let lo=0,hi=values.length-1;\n  while(lo<=hi){\n    const mid=Math.floor((lo+hi)/2);\n    if(values[mid]===target)return mid;\n    if(values[mid]<target)lo=mid+1;else hi=mid-1;\n  }\n  return -1;\n}',
walkthrough:['The algorithm assumes values are sorted.','Each comparison discards half of the remaining search space.','The loop invariant is that if target exists, it remains within the active range.','Termination occurs when the range becomes empty or the target is found.'],
failures:['Applying binary search to unsorted data.','Forgetting empty input and duplicate behavior.','Writing a loop without a termination argument.','Optimizing before proving the algorithm matches the requirement.'],
performance:'Binary search is logarithmic in comparisons under its assumptions, but obtaining sorted data may itself cost time. The end-to-end workload matters more than one isolated operation.',
security:'Algorithmic complexity can become a security issue when attackers control input size. Avoid accidental quadratic behavior in request paths and validate expensive operations.',
accessibility:'Algorithms that drive UI ordering, focus traversal or filtering must preserve predictable interaction and meaningful sequence.',
production:'State algorithmic preconditions, cap expensive work, test worst-case inputs and instrument expensive paths.',
debugging:['Construct the smallest failing input.','Check preconditions.','Trace one iteration at a time.','Verify the loop invariant.','Add boundary tests.'],
exercises:['Implement linear and binary search and compare them on sorted inputs.','Implement BFS for a graph.','Find duplicates using nested loops and then using Set; compare complexity.'],
mastery:'You can design, prove informally, test and analyze algorithms rather than merely memorize implementations.',
quiz:[['What precondition does binary search require?','A sorted search space.'],['Why is an invariant useful?','It provides a property that remains true and supports correctness reasoning.'],['What should be tested besides the happy path?','Empty, boundary, duplicate, malformed and large inputs.']]
},
'complexity':{
level:'Deep Dive → Performance',prerequisites:['Algorithms','Data Structures'],objectives:['Estimate time and space growth.','Recognize common complexity classes.','Use complexity as a design constraint without treating it as exact runtime.'],
problem:'Scale changes software behavior. A solution that is acceptable for 100 records can fail catastrophically at 10 million.',
history:'As computing moved from small datasets to large systems, asymptotic analysis became a practical way to compare algorithm growth independently of one machine’s exact speed.',
think:'Focus on growth. Ask what happens when input doubles, becomes ten times larger, or becomes attacker-controlled. Then identify the operation responsible for that growth.',
concepts:[['O(1)','Bounded work independent of input size under the stated model.'],['O(log n)','Work grows slowly because each step substantially reduces the search space.'],['O(n)','Work grows proportionally with input size.'],['O(n log n)','Common in efficient comparison-based sorting.'],['O(n²)','Often produced by nested comparisons over the same input.'],['Space complexity','How additional memory requirements grow with input.']],
flow:['Define input size.','Count dominant operations.','Express growth.','Consider auxiliary memory.','Check constants and real-world bottlenecks.','Benchmark representative workloads.'],
example:'function hasDuplicate(values){\n  const seen=new Set();\n  for(const value of values){\n    if(seen.has(value))return true;\n    seen.add(value);\n  }\n  return false;\n}',
walkthrough:['The loop processes each item at most once.','Set provides expected fast membership lookup.','The algorithm uses additional memory proportional to distinct values.','The result is expected O(n) time and O(n) auxiliary space.'],
failures:['Treating Big O as exact milliseconds.','Ignoring space complexity.','Ignoring I/O and database behavior.','Assuming a theoretically faster algorithm is always faster in every workload.'],
performance:'Real performance includes constants, cache locality, allocations, JIT optimization, network latency, database query plans and storage behavior. Complexity tells you about growth; profiling tells you where the actual time goes.',
security:'Complexity attacks exploit expensive algorithms with adversarial input. Rate limits, input caps, bounded parsing and algorithmic safeguards are security controls.',
accessibility:'Slow client-side filtering, rendering or event handlers directly affect interaction latency. Complexity is therefore part of perceived accessibility.',
production:'Set explicit limits for payload size, query depth, result counts and batch work. Monitor latency distributions, not only averages.',
debugging:['Measure input size.','Profile the dominant path.','Compare operation counts.','Inspect allocations and I/O.','Test scaling behavior rather than one small sample.'],
exercises:['Benchmark duplicate detection with nested loops versus Set.','Plot runtime against input size for several algorithms.','Identify one O(n²) operation in a hypothetical API and redesign it.'],
mastery:'You can estimate growth, explain trade-offs and use measurement to connect asymptotic reasoning to production behavior.',
quiz:[['What does O(n) describe?','Work growing proportionally with input size.'],['Does O(1) mean zero time?','No; it means bounded growth under the chosen model.'],['Why can a faster asymptotic algorithm lose on small inputs?','Constants, overhead and implementation details can dominate at small scale.']]
},
'cli-editor-debugger':{
level:'Practice → Developer Workflow',prerequisites:['Programming Fundamentals'],objectives:['Navigate and manipulate projects from a terminal.','Use a debugger and logs as evidence.','Build reproducible debugging workflows.'],
problem:'Professional development is an iterative loop: inspect, change, run, test, observe, diagnose and repeat. Tool fluency determines how quickly you can complete that loop.',
history:'Command-line tools became central to Unix development because composable commands provide automation and reproducibility. Modern editors and IDEs add rich navigation, debugging and testing while retaining the same underlying execution model.',
think:'Use tools as observation surfaces. The terminal tells you what environment and commands exist; the editor changes the system; the debugger exposes runtime state; tests provide repeatable evidence.',
concepts:[['Shell','Program that interprets commands and launches processes.'],['Path','A location identifying a file or directory.'],['Environment variable','Process configuration supplied through the execution environment.'],['Breakpoint','A deliberate pause point for inspecting runtime state.'],['Call stack','The chain of active function calls leading to the current execution point.'],['Regression test','An automated check preventing a known failure from returning.']],
flow:['Reproduce.','Capture the exact command and input.','Observe output and logs.','Pause at the relevant state.','Identify the first incorrect transition.','Fix the cause.','Run regression tests.'],
example:'function divide(a,b){\n  if(b===0)throw new Error(\'division by zero\');\n  return a/b;\n}\nconsole.log(divide(10,2));',
walkthrough:['The function establishes an explicit invalid-input rule.','A debugger can inspect a and b before division.','The thrown error creates a visible failure rather than silently returning an invalid result.','A test can lock the contract in place.'],
failures:['Changing random lines without reproducing the issue.','Debugging from screenshots without commands or inputs.','Logging secrets.','Deleting the failing code before understanding the cause.'],
performance:'Developer time is also a resource. Fast feedback loops, targeted tests and reproducible commands reduce cycle time and make performance investigations more reliable.',
security:'Never paste secrets into source, logs, issues or shell history. Treat environment variables as configuration, not as a guarantee that secrets are safe everywhere.',
accessibility:'Developer tooling itself should support keyboard workflows, readable diagnostics and clear focus behavior; accessible tools reduce barriers to maintaining accessible products.',
production:'Use structured logs, correlation identifiers, safe error messages, health endpoints, reproducible commands and automated tests. Keep diagnostic detail separate from sensitive user-facing output.',
debugging:['Reproduce exactly.','Minimize the input.','Inspect state at the first suspicious transition.','Form one hypothesis.','Test the hypothesis.','Fix and add a regression test.'],
exercises:['Create a disposable directory and practice pwd, ls, cd, mkdir, cp, mv and rm.','Set and read an environment variable.','Debug a deliberately failing function and write the evidence chain.'],
mastery:'You can investigate software failures systematically and leave behind reproducible evidence and a regression test.',
quiz:[['What is a breakpoint for?','Pausing execution to inspect runtime state.'],['What should a good debugging process start with?','A reproducible failure and its exact input/environment.'],['Why avoid secrets in logs?','Logs can be broadly accessible and retained longer than expected.']]
}
};
window.FULLSTACK_DEEP_CONTENT=D;
})();
